### PR TITLE
Added smoother page transitions (and updated .gitignore for Jetbrains Rider users)

### PR DESCRIPTION
**Pull request by CXCubeHD**
https://user-images.githubusercontent.com/49782272/127213824-50c4c38d-1c15-44d1-ad09-da15db9df1e7.mp4

I could add an option to adjust the speed maybe next time...

### CODE REVIEW

**Comment by CarJem** [comment]
@CXCubeHD I would like to speak to you about some things please....

**Comment by CoolAbhi1290** [comment]
Wouldn't this make Bedrock Launcher not in parity with the official one?

**Comment by CarJem** [comment]
> Wouldn't this make Bedrock Launcher not in parity with the official one?

That too... but more importantly there are issues with it being able to build... so I went about correcting these issues and will post my changes shortly

**Comment by CarJem** [comment]
I've disabled the smoother page animations because they're not on parity with Java Launcher... however, I have not removed them entirely... I will be considering implementing them after the merge as a separate setting...

**Comment by CXCubeHD** [comment]
@CarJem I think that making a setting for it is very good, I wanted to make it but I know that my code for the ui settings page wouldn't fit with yours
👍

**Pull request merged**
