### PR TITLE
Logo updates

### PR DESCRIPTION
**Pull request by MetalManiacMc**
Updated Minecraft logos to match... Minecraft.

### CODE REVIEW

**Comment by MetalManiacMc** [comment]
I have noticed some sizing error I will fix

**Comment by tresabhi** [comment]
@MetalManiacMc is this finalized?

**Comment by MetalManiacMc** [comment]
No, not yet, Ill try to get it done this weekend.

**Comment by MetalManiacMc** [comment]
'Tis done!

**Pull request merged**
